version: '2'
services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
    - 2181:2181
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
    - 9092:9092
    environment:
      KAFKA_CREATE_TOPICS: baeldung:1:1,partitioned:5:1,filtered:1:1,greeting:1:1
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.101
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.101:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
    - zookeeper